datasets:
- ccd
- cis
- ecg
- ehr
- scdb
clean_path: /Users/Wesley/data/nuhs/csv/clean
raw_path: /Users/Wesley/data/nuhs/csv/raw
preprocessed_path: /Users/Wesley/data/nuhs/csv/preprocessed
chunksize: 10000