cis.cag:
#- Study Num
#- IDRef
#- IDRef_sha2
#- Procedure Date
- Comments
- Case Closed Date
- HTML
- ScrubNurse1
- ScrubNurse2
- Radiographer
cis.caglesion:
#- Study Num
#- IDRef
#- IDRef_sha2
#- Procedure Date
cis.caglesionpivoted:
#- IDRef
#- Procedure Date
#- Study Num
cis.echo:
#- Study Num
#- IDRef
#- IDRef_sha2
#- Procedure Date
- Case Closed Date
- Test Report
- OriginalStudyNum
- RF_IDRef
- UniqueID
- StaffNurse
cis.nuclear:
#- IDRef
#- Procedure Date
- Proc_HospitalID
- ResCode
#- Study Num
- StudyID
- Most_recent_MI
- Date_of_last_PTCA
- Date_of_last_CABG
- Previous_Nuclear_Study_Date
- Previous_Nuclear_Study_Done_in
- Case Closed Date
- TempStudyNo
- HTML
- RF_IDRef
- UniqueID
- Radiographer
- StaffNurse
cis.pacemaker:
#- Study Num
#- IDRef
#- IDRef_sha2
#- Procedure Date
- Proc_HospitalID
- ResCode
- Original Study Num
- Case Closed Date
- Serial No
- Comments
- Explant_Serial Number
- HTML
- id_Study
- UniqueID
- Past_PrevCABGProcDate
- Past_PrevPTCAProcDate
- Procedure_Date
- Procedure_Hospital
- ProcedureStartTime
- ProcedureEndTime
- Radiographer
- ScrubNurse
- CirculatingNurse
cis.pci:
#- IDRef
#- Procedure Date
- Proc_HospitalID
- ResCode
#- Study Num
- Original Study Num
- PTCA_ID
- Admission_Date
- Discharge_Date
- Staff_Nurse
- Radiographer
- IIBIIIA_Date
#- Cx_Date
#- Date_of_Death
- Hospital
- Case Closed Date
#- Time_Start
#- Time_End
#- Time_EMD
#- Time_ACT
#- Time_Balloon
#- Date_ACT
#- Date_Balloon
#- Date_EMD
#- Date_NUH_Arr_FromOtherHos
#- Time_NUH_Arr_FromOtherHos
#- Time_Arr_OtherHos
#- Date_Arr_OtherHos
- Anaesthetist
- Sonographer3
- Surgeon1
- Surgeon2
- Echocardiologist
#- Time_ArriveCathlab
#- Date_ArriveCathlab
- RF_IDRef
#- Timeout_NTFGH
#- Triage_time_at_NUH_ED
- UniqueID
- Circulating_Nurse
- OctID
#- Time_SymptomOnset
#- Time_SeekMedAtt
#- Time_FirstMedCon
#- Date_SymptomOnSet
#- Date_SeekMedAtt
#- Date_FirstMedCon
cis.pcidevicesequence:
#- Study Num
#- IDRef
#- IDRef_sha2
- PTCA_Export_ID
#- Procedure Date
- Combined_Serial
- UniqueID
cis.pcidevicesequencetimings:
#- Study Num
#- IDRef
#- IDRef_sha2
- PTCA_Export_Sequence_ID
#- Procedure Date
- Proc_HospitalID
#- Start_Time
#- End_Time
#- Elapsed_Time
- PTCA_ID
- Start_Date
- PTCA_Export_ID
cis.pcilesionsequence:
#- Study Num
#- IDRef
#- IDRef_sha2
#- Procedure Date
- PTCA_ID
- Serial_No
- Serial2
- Combined_Serial
- PTCA_Export_ID
- UniqueID
cis.procedure:
#- Study Num
#- IDRef
#- IDRef_sha2
- Referring Dr
- Supervising Dr
- Sonographer
#- Procedure Date
- Tape Code
- Tape Number1
- Case Closed Date
- Original Study Num
- Supervising Dr2
- Sonographer2
- Tape Number2
- RoomNo
- Counter1
- Counter2
- Age
- ProcTimeIn
- ProcTimeOut
- ProcedureID
- Age_date
- Supervising Dr3
- Supervising Dr4
- AmendedDate
- HospitalID
- ClosedBy
- ReopenBy
- OrganizationalUnitName
- sapRoomNo
- sapBedNo
- sapReferringDr
- sapAdmittingDr
- sapAttendingDr
- sapDischargeDr
- CostCtr_grp
- HTML_ID
- DerivedStudyNumber
- Nurse
- MCR_SupervisingDr
- MCR_SupervisingDr2
- MCR_SupervisingDr3
- MCR_SupervisingDr4
- sapPatientVisitNo
- MCR_sapReferringDr
- MCR_sapAttendingDr
- MCR_ReferringDr
- Proc_CaseNo
- Proc_HospitalID
- MCR_sapAdmittingDr
- MCR_sapDischargeDr
- MovementNo